import jsPDF from 'jspdf';
import type { ReportSection, ReportMeta, MetricStatus } from '../types/index';

export function generateReport(sections: ReportSection[], meta: ReportMeta): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = 210;
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 20;

  function checkPage(needed = 10) {
    if (y + needed > 275) { doc.addPage(); y = 20; }
  }

  const statusColors: Record<MetricStatus, [number, number, number]> = {
    green: [34, 197, 94],
    amber: [245, 158, 11],
    red: [239, 68, 68],
    unknown: [150, 150, 150],
  };

  // Header
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(meta.title, margin, y);
  y += 8;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Date: ${meta.date}`, margin, y);
  doc.text(`Generated: ${new Date().toLocaleTimeString()}`, margin + 60, y);
  if (meta.clientName) doc.text(`Client: ${meta.clientName}`, margin + 120, y);
  y += 6;

  // Logo placeholder
  doc.setDrawColor(200, 200, 200);
  doc.rect(pageWidth - margin - 45, 10, 45, 18);
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Clinic Logo', pageWidth - margin - 22, 20, { align: 'center' });
  doc.setTextColor(0, 0, 0);

  // Sections
  for (const section of sections) {
    checkPage(20);
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.text(section.title, margin, y);
    y += 7;

    if (section.image) {
      const imgW = Math.min(contentWidth, 120);
      const imgH = imgW / section.image.aspectRatio;
      checkPage(imgH + 6);
      doc.addImage(section.image.dataUrl, 'JPEG', margin, y - 3, imgW, imgH);
      y += imgH + 4;
    }

    if (section.metrics.length > 0) {
      // Table header
      doc.setFontSize(8);
      doc.setFillColor(240, 240, 240);
      doc.rect(margin, y - 4, contentWidth, 6, 'F');
      doc.setFont('helvetica', 'bold');
      doc.text('Metric', margin + 2, y);
      doc.text('Value', margin + 85, y);
      doc.text('Status', margin + 110, y);
      doc.text('Normal Range', margin + 135, y);
      y += 4;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);

      for (const { label, result, normalRange } of section.metrics) {
        checkPage(6);
        const color = statusColors[result.status];
        doc.setFillColor(...color);
        doc.circle(margin + 107, y - 1.5, 1.5, 'F');
        doc.setFillColor(0, 0, 0);

        doc.text(label, margin + 2, y);
        doc.text(`${result.value.toFixed(1)}${result.unit}`, margin + 85, y);
        doc.text(result.status.toUpperCase(), margin + 112, y);
        doc.text(normalRange ?? '—', margin + 135, y);
        y += 6;
      }
      y += 4;
    }

    if (section.findings.length > 0) {
      checkPage(10);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text('Findings', margin, y);
      y += 5;

      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      for (const finding of section.findings) {
        const lines = doc.splitTextToSize(finding, contentWidth - 8);
        checkPage(lines.length * 5 + 6);
        doc.setFillColor(245, 158, 11);
        doc.rect(margin, y - 4, 2, lines.length * 5 + 2, 'F');
        doc.setFillColor(0, 0, 0);
        doc.text(lines, margin + 5, y);
        y += lines.length * 5 + 4;
      }
      y += 4;
    }
  }

  // Session notes
  if (meta.notes.trim()) {
    checkPage(15);
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.text('Session Notes', margin, y);
    y += 7;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    const noteLines = doc.splitTextToSize(meta.notes, contentWidth);
    checkPage(noteLines.length * 5);
    doc.text(noteLines, margin, y);
    y += noteLines.length * 5;
  }

  // Footer on every page
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by ${meta.appName} — on-device analysis, no data transmitted | Page ${i} of ${pageCount}`,
      pageWidth / 2,
      290,
      { align: 'center' },
    );
    doc.setTextColor(0, 0, 0);
  }

  const filename = `${meta.appName.toLowerCase()}-report-${Date.now()}.pdf`;
  doc.save(filename);
}
