import jsPDF from 'jspdf';
import { METRIC_LABELS, APP_NAME } from '../config/defaults';
import { THRESHOLDS } from '../analysis/thresholds';
import type { ReportParams, AnalysisResults } from '../analysis/types';

export function generateReport(params: ReportParams): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = 210;
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 20;

  function checkPage(needed = 10) {
    if (y + needed > 275) { doc.addPage(); y = 20; }
  }

  // Header
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Running Gait Analysis Report', margin, y);
  y += 8;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Date: ${new Date().toLocaleDateString()}`, margin, y);
  doc.text(`Generated: ${new Date().toLocaleTimeString()}`, margin + 60, y);
  if (params.clientName) doc.text(`Client: ${params.clientName}`, margin + 120, y);
  y += 6;

  // Logo placeholder
  doc.setDrawColor(200, 200, 200);
  doc.rect(pageWidth - margin - 45, 10, 45, 18);
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Clinic Logo', pageWidth - margin - 22, 20, { align: 'center' });
  doc.setTextColor(0, 0, 0);

  // Key frame screenshot
  if (params.frameDataUrl) {
    checkPage(65);
    doc.addImage(params.frameDataUrl, 'PNG', margin, y, contentWidth, 80);
    y += 83;
  }

  // Metrics table
  checkPage(15);
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Metrics Summary', margin, y);
  y += 7;

  // Table header
  doc.setFontSize(8);
  doc.setFillColor(240, 240, 240);
  doc.rect(margin, y - 4, contentWidth, 6, 'F');
  doc.setFont('helvetica', 'bold');
  doc.text('Metric', margin + 2, y);
  doc.text('Value', margin + 85, y);
  doc.text('Status', margin + 110, y);
  doc.text('Normal Range', margin + 135, y);
  y += 4;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);

  for (const [key, result] of Object.entries(params.metrics) as [keyof AnalysisResults, typeof params.metrics[keyof AnalysisResults]][]) {
    if (!result) continue;
    checkPage(6);

    const threshold = THRESHOLDS[key];
    const label = METRIC_LABELS[key] ?? key;
    const range = threshold
      ? `${threshold.green[0]}–${threshold.green[1]}${threshold.unit}`
      : '—';

    // Status colour dot
    const statusColors: Record<string, [number, number, number]> = {
      green: [34, 197, 94],
      amber: [245, 158, 11],
      red: [239, 68, 68],
    };
    const color = statusColors[result.status] ?? ([150, 150, 150] as [number, number, number]);
    doc.setFillColor(...color);
    doc.circle(margin + 107, y - 1.5, 1.5, 'F');
    doc.setFillColor(0, 0, 0);

    doc.text(label, margin + 2, y);
    doc.text(`${result.value.toFixed(1)}${result.unit}`, margin + 85, y);
    doc.text(result.status.toUpperCase(), margin + 112, y);
    doc.text(range, margin + 135, y);
    y += 6;
  }

  y += 4;

  // Findings
  if (params.findings.length > 0) {
    checkPage(15);
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.text('Clinical Findings', margin, y);
    y += 7;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    for (const finding of params.findings) {
      const lines = doc.splitTextToSize(finding.text, contentWidth - 8);
      checkPage(lines.length * 5 + 6);

      const barColor: [number, number, number] = finding.status === 'red'
        ? [239, 68, 68]
        : [245, 158, 11];
      doc.setFillColor(...barColor);
      doc.rect(margin, y - 4, 2, lines.length * 5 + 2, 'F');
      doc.setFillColor(0, 0, 0);

      doc.text(lines, margin + 5, y);
      y += lines.length * 5 + 4;
    }
    y += 4;
  }

  // Physio notes
  if (params.notes.trim()) {
    checkPage(15);
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.text('Session Notes', margin, y);
    y += 7;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    const noteLines = doc.splitTextToSize(params.notes, contentWidth);
    checkPage(noteLines.length * 5);
    doc.text(noteLines, margin, y);
    y += noteLines.length * 5;
  }

  // Footer on every page
  const pageCount = (doc as unknown as { getNumberOfPages: () => number }).getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by ${APP_NAME} — on-device analysis, no data transmitted | Page ${i} of ${pageCount}`,
      pageWidth / 2,
      290,
      { align: 'center' },
    );
    doc.setTextColor(0, 0, 0);
  }

  doc.save(`runalyze-report-${Date.now()}.pdf`);
}
